a=4;
b=4.5;
c="Adil";
d='e';
e=true;
console.log(a,typeof(a));//number
console.log(b,typeof(b));//number
console.log(c,typeof(c));//string
console.log(d,typeof(d));//string   
console.log(e,typeof(e));   